fhtt\entities\Program:
    type: entity
    id:
        id:
            type: integer
            generator: 
                strategy: AUTO
    fields:
        short: 
            type: string
            length: 10
        name:
            type: string
            length: 100
    oneToMany: 
        modules:
            targetEntity: Module
            mappedBy: program
        
